name: Deploy to Artifactory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      RELEASE_REPO: ${{ secrets.RELEASE_REPO }}
      SNAPSHOT_REPO: ${{ secrets.SNAPSHOT_REPO }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build and deploy with custom settings.xml
        run: ./mvnw --batch-mode -s settings.xml clean deploy
